kind: Deployment
apiVersion: apps/v1
metadata:
   name: healthcheck
spec:
   replicas: 1
   selector:      
    matchLabels:
     wezvatech: adam
   template:
     metadata:
       name: healthprobe
       labels:
         wezvatech: adam
     spec:
      containers:
        - name: main
          image: httpd
          ports:
           - containerPort: 80
          livenessProbe:                  
           exec:
             command:                   
             - ls
             - /tmp/lp
           initialDelaySeconds: 30
           periodSeconds: 5       
           timeoutSeconds: 10
