kind: Deployment
apiVersion: apps/v1
metadata:
   name: service
spec:
   replicas: 2
   selector:      
    matchLabels:
     wezvatech: adam
   template:
     metadata:
       name: serviceerr
       labels:
         wezvatech: adam
     spec:
      containers:
        - name: main
          image: httpd
          ports:
           - containerPort: 80
---
kind: Service                             
apiVersion: v1
metadata:
  name: demoservice
spec:
  ports:
    - port: 80                              
      targetPort: 80                    
  selector:
    wezvatech: ninjasprogram
  type: ClusterIP
