kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myebsvolclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pvdeploy
spec:
  replicas: 1
  selector:     
    matchLabels:
     wezvatech: adam
  template:
    metadata:
      name: pvd
      labels:
        wezvatech: adam
    spec:
      containers:
      - name: main
        image: centos
        command: ["/bin/bash", "-c", "sleep 10000"]
        volumeMounts:
        - name: mypd
          mountPath: "/tmp/persistent"
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: myebsvolclaim

